USE [NIHF];
GO

/****** Object:  Table [dbo].[Manufacturer]    Script Date: 5/10/2019 2:17:23 PM ******/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[Manufacturer]
([ID]   [INT] IDENTITY(1, 1) NOT NULL, 
 [Name] [NVARCHAR](50) NOT NULL, 
 CONSTRAINT [PK_Manufacturer] PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO